# Project
version=1.2.0
group=com.evandev.packdev_toolkit
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Packdev Toolkit
mod_author=Evan
mod_id=packdev_toolkit
license=MIT
credits=
description=A collection of developer tools for building modpacks and datapacks. Pull textures/models out of resource packs, dump lang entries, search datapacks, and copy item IDs: all without leaving the game!
minecraft_version_range=[1.21.1, 1.21.2)
neo_form_version=1.21.1-20240808.144430

# Parchment
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Dependencies
yacl_version=3.8.2+1.21.1
mod_menu_version=11.0.3
emi_version=1.1.22+1.21.1
item_descriptions_version=2.7.2+1.21.1

# Fabric
fabric_version=0.116.7+1.21.1
fabric_loader_version=0.18.3

# NeoForge
neoforge_version=21.1.181
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false